name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        scan_type: filesystem
        path: .
        extra_args: --results=verified,unknown

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build AndroidTest APK
      run: ./gradlew assembleDebugAndroidTest

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload AndroidTest APK
      uses: actions/upload-artifact@v4
      with:
        name: androidtest-apk
        path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  test:
    needs: build

    permissions:
      checks: write # required for mikepenz/action-junit-report
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Download Debug APK
      uses: actions/download-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug

    - name: Download AndroidTest APK
      uses: actions/download-artifact@v4
      with:
        name: androidtest-apk
        path: app/build/outputs/apk/androidTest/debug

    - name: Run Unit Tests
      run: |
        ./gradlew testDebugUnitTest | tee unit-test.log
        EXIT=${PIPESTATUS[0]}
        [ $EXIT -eq 0 ] || cat unit-test.log
        exit $EXIT

    - name: Upload Unit Test Report
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-report
        path: app/build/reports/tests/testDebugUnitTest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Run Firebase Test Lab tests
      run: |
        gcloud firebase test android run \
          --type instrumentation \
          --app app/build/outputs/apk/debug/app-debug.apk \
          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          --device model=redfin,version=30 \
          --timeout 5m \
          --results-dir="instrumentation-test-results" \
          --results-bucket=gs://instrumentation-test-results          

    - name: Download results from Firebase Test Lab
      run: |
        mkdir -p testlab-results
        gsutil -m cp -r gs://instrumentation-test-results/instrumentation-test-results testlab-results/

    - name: Upload Instrumented Test Report
      uses: actions/upload-artifact@v4
      with:
        name: firebase-testlab-results
        path: testlab-results

    - name: Publish Unit Test Results
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: app/build/test-results/testDebugUnitTest/*.xml
        check_name: "Unit Test Results"

    - name: Publish Instrumented Test Results
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: testlab-results/instrumentation-test-results/**/*.xml
        check_name: "Instrumented Test Results"

    - name: Run Android Lint
      run: ./gradlew lintDebug

    - name: Upload Lint Report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: app/build/reports/lint-results-debug.html

    - name: Run Detekt
      run: |
        ./gradlew detekt | tee detekt.log
        EXIT=${PIPESTATUS[0]}
        [ $EXIT -eq 0 ] || cat detekt.log
        exit $EXIT

    - name: Upload Detekt Log
      uses: actions/upload-artifact@v4
      with:
        name: detekt-log
        path: detekt.log

    - name: Upload Detekt Report
      uses: actions/upload-artifact@v4
      with:
        name: detekt-report
        path: app/build/reports/detekt/detekt.html

    - name: Generate Kover XML Report
      run: ./gradlew koverXmlReport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: app/build/reports/kover/report.xml
        fail_ci_if_error: true

  delivery:
    needs: test

    permissions:
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - name: Distribute to Firebase Testers
      run: |
        firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --groups "qa-team"
